# Generated by Django 5.0.3 on 2024-05-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image_subject',
            field=models.ImageField(default='course_images/default.jpg', upload_to='course_images'),
        ),
    ]
