# Generated by Django 5.0.3 on 2024-05-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_title_alter_lesson_video_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Klasa',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='classroom',
            new_name='klasa',
        ),
    ]
