# Generated by Django 5.0.3 on 2024-05-19 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_class_klasa_rename_classroom_subject_klasa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Lendet',
        ),
    ]
